[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
install_requires = [
    "h5netcdf",
    "netcdf4",
    "h5py",
    "scipy",
    "xarray",
    "matplotlib"
]
build-backend = "setuptools.build_meta"